/**
 * Canonical list of all bundled patch names.
 * Single source of truth -- used by TilesetPanel dropdown and batch renderer.
 */
export const BUNDLED_PATCHES: readonly string[] = [
  'AC Default',
  'Apple',
  'AS',
  'Bile Patch',
  'Black Magic',
  'Black Tiles',
  'Blue Widow',
  'bouncy-patch',
  'Cert Patch',
  'Charlie',
  'Club Purr',
  'forest-patch',
  'Gold',
  'Gold2',
  'H-Front',
  'High Contrast',
  'Hockey',
  'lil-knights-by-aTreYu',
  'LN Patch',
  'Mr Bandwidth',
  'nBn Patch',
  'NextGEN - Battle for Earth',
  'NextGEN -APL',
  'NextGEN -Cell Shade',
  'NextGEN -Final',
  'NextGEN -Initial Confrontation',
  'NextGEN -TBWA Edition v2',
  'ota-patch',
  'Perfection',
  'Precious Metals',
  'Rage',
  'Retro Patch',
  'Sierra ARC',
  'Siren Patch',
  'Solo Style',
  'Spark 3D',
  'Star Gaze',
  'Tek',
  'TEN Patch',
  'Trooper',
  'Trooper v2',
  'uFo Patch',
  'waves-patch',
] as const;
